//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricBook.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatch
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Team_A { get; set; }
        public Nullable<int> Team_B { get; set; }
        public string Venue_Details { get; set; }
        public Nullable<System.DateTime> MatchDatetime { get; set; }
        public Nullable<int> MatchType { get; set; }
        public Nullable<int> MatchWonby { get; set; }
        public string Result { get; set; }
        public Nullable<int> MOM { get; set; }
        public Nullable<int> GameType { get; set; }
    
        public virtual tblGameType tblGameType { get; set; }
        public virtual tblMatchType tblMatchType { get; set; }
        public virtual tblTeam tblTeam { get; set; }
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblTeam tblTeam1 { get; set; }
        public virtual tblTeam tblTeam2 { get; set; }
    }
}
